services:
  postgres:
    image: postgres:14.5
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  products-service:
    image: node:16.14.0-alpine3.14
    command:
      [
        "yarn",
        "workspace",
        "products-service",
        "run",
        "start:dev"
      ]
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  postgres:
